"""Exact compact SAT lift for the three exhaustive local E0=77 orbits.

The local representatives are generated by ``scratch_e77_sat_reps.py``.
For each representative this model fixes every same-support edge and every
edge between overlapping exceptional fibres.  Edges between disjoint support
fibres remain variables.  Ordinary C4 fibres imply exact one-sided block
constraints; a two-sided permutation is imposed only when both fibres are
ordinary C4s.  All BP equalities and every outer-pair common-neighbour
equality are then encoded exactly.

No solver result here is treated as a formal proof unless a separately
checked certificate is produced.  A SAT assignment is expanded to all 99
vertices and independently verified; this script never writes submission.txt.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import multiprocessing as mp
import queue
import time
from pathlib import Path

from scratch_general_exact_sat import coordinates, verify


REPS_PATH = Path("scratch_e77_sat_reps.json")
BUILD_PATH = Path("scratch_e77_sat_exact_build.json")
RESULT_PATH = Path("scratch_e77_sat_exact_portfolio.json")


def source_data():
    source = json.loads(REPS_PATH.read_text(encoding="utf-8"))
    assert source["ok"] and source["surviving_local_orbits"] == 3
    rows = [row for row in source["rows"] if row["local_orbit_count"]]
    assert len(rows) == 1
    row = rows[0]
    assert row["source_orbit_index"] == 22
    assert len(row["representatives"]) == 3
    return row


def build_cnf(branch_index, write_dimacs=False):
    from pysat.card import CardEnc, EncType
    from pysat.formula import IDPool

    source = source_data()
    representative = source["representatives"][branch_index]
    labels, label_index, full_variables, _full_edge = coordinates()
    supports = tuple(tuple(symbol // 2 for symbol in label) for label in labels)
    signs = tuple({symbol // 2: symbol % 2 for symbol in label} for label in labels)
    fibres = {
        support: tuple(u for u, value in enumerate(supports) if value == support)
        for support in itertools.combinations(range(7), 2)
    }
    exceptional = frozenset(tuple(support) for support in source["supports"])
    high = frozenset(set(fibres) - set(exceptional))
    assert len(exceptional) == 7 and len(high) == 14

    local_graph_labels = frozenset(
        tuple(sorted((tuple(edge[0]), tuple(edge[1]))))
        for edge in representative["local_graph_edges"]
    )
    assert len(local_graph_labels) == representative["edge_count"] == 35
    local_graph = frozenset(
        tuple(sorted((label_index[u], label_index[v])))
        for u, v in local_graph_labels
    )

    pool = IDPool(start_from=1)
    edge_variables = {}
    disjoint_blocks = []
    for A, B in itertools.combinations(fibres, 2):
        if set(A).isdisjoint(B):
            disjoint_blocks.append((A, B))
            for u in fibres[A]:
                for v in fibres[B]:
                    key = tuple(sorted((u, v)))
                    assert key not in edge_variables
                    edge_variables[key] = pool.id(("edge",) + key)

    def edge(u, v):
        if u == v:
            return False
        key = tuple(sorted((u, v)))
        if key in edge_variables:
            return edge_variables[key]
        A, B = supports[u], supports[v]
        if A == B:
            if A in exceptional:
                return key in local_graph
            # Every ordinary fibre is the coordinate-square C4.
            return sum(signs[u][group] != signs[v][group] for group in A) == 1
        if set(A) & set(B):
            if A in exceptional and B in exceptional:
                return key in local_graph
            # An ordinary C4 saturates all quotas in either shared group.
            return False
        raise AssertionError("every disjoint block must be variable")

    clauses = []

    def exactly_one(literals):
        assert literals and all(type(value) is int for value in literals)
        clauses.append(list(literals))
        clauses.extend([-u, -v] for u, v in itertools.combinations(literals, 2))

    high_high_blocks = high_low_blocks = low_low_blocks = 0
    exact_one_rows = exact_one_columns = 0
    for A, B in disjoint_blocks:
        if A in high and B in high:
            high_high_blocks += 1
        elif A in high or B in high:
            high_low_blocks += 1
        else:
            low_low_blocks += 1
        # For every ordinary C4 H and every disjoint outside vertex x,
        # x has exactly one neighbour in H.  Applying this from each high
        # endpoint gives a permutation only in the high-high case.
        if A in high:
            for v in fibres[B]:
                exactly_one([edge(u, v) for u in fibres[A]])
                exact_one_columns += 1
        if B in high:
            for u in fibres[A]:
                exactly_one([edge(u, v) for v in fibres[B]])
                exact_one_rows += 1

    cardinality_equalities = 0

    def add_exact(expressions, wanted):
        nonlocal cardinality_equalities
        fixed = sum(value is True for value in expressions)
        literals = [value for value in expressions if type(value) is int]
        target = wanted - fixed
        cardinality_equalities += 1
        if target < 0 or target > len(literals):
            clauses.append([])
        elif not literals:
            if target:
                clauses.append([])
        else:
            clauses.extend(
                CardEnc.equals(
                    literals,
                    target,
                    vpool=pool,
                    encoding=EncType.seqcounter,
                ).clauses
            )

    # BP = PA0: exact symbol quotas for every outer vertex.
    for u, label in enumerate(labels):
        own = set(label)
        for symbol in range(14):
            add_exact(
                [
                    edge(u, v)
                    for v, other in enumerate(labels)
                    if u != v and symbol in other
                ],
                1 if symbol in own or (symbol ^ 1) in own else 2,
            )

    products = direct_terms = constant_terms = 0
    pair_target_histogram = {1: 0, 2: 0}
    for u, v in itertools.combinations(range(84), 2):
        expressions = [edge(u, v)]
        for w in range(84):
            if w in (u, v):
                continue
            a, b = edge(u, w), edge(v, w)
            if a is False or b is False:
                continue
            if a is True and b is True:
                expressions.append(True)
                constant_terms += 1
            elif a is True:
                expressions.append(b)
                direct_terms += 1
            elif b is True:
                expressions.append(a)
                direct_terms += 1
            elif a == b:
                expressions.append(a)
                direct_terms += 1
            else:
                z = pool.id(("and", u, v, w))
                # Exact z <-> (a & b), required because the sum is equality.
                clauses.extend(([-a, -b, z], [a, -z], [b, -z]))
                expressions.append(z)
                products += 1
        target = 2 - len(set(labels[u]) & set(labels[v]))
        pair_target_histogram[target] += 1
        add_exact(expressions, target)

    # Structural audits on all fixed local entries.
    internal_fixed = overlap_fixed = 0
    for u, v in local_graph:
        A, B = supports[u], supports[v]
        if A == B:
            internal_fixed += 1
        else:
            assert set(A) & set(B)
            overlap_fixed += 1
    assert (internal_fixed, overlap_fixed) == (21, 14)

    meta = {
        "model": "exact compact E0=77 lift with exhaustive fixed local representative",
        "branch_index": branch_index,
        "source_support_orbit": source["source_orbit_index"],
        "local_representative_multiplicity": representative["multiplicity_in_enumeration"],
        "exceptional_supports": [list(support) for support in sorted(exceptional)],
        "ordinary_c4_fibres": len(high),
        "fixed_local_internal_edges": internal_fixed,
        "fixed_local_overlap_edges": overlap_fixed,
        "disjoint_blocks": len(disjoint_blocks),
        "high_high_permutation_blocks": high_high_blocks,
        "high_low_one_sided_blocks": high_low_blocks,
        "unrestricted_low_low_disjoint_blocks": low_low_blocks,
        "exact_one_rows": exact_one_rows,
        "exact_one_columns": exact_one_columns,
        "edge_variables": len(edge_variables),
        "product_variables": products,
        "direct_product_terms": direct_terms,
        "constant_product_terms": constant_terms,
        "pair_target_histogram": pair_target_histogram,
        "cardinality_equalities": cardinality_equalities,
        "variables": pool.top,
        "clauses": len(clauses),
        "coverage": (
            "one of three exhaustive local symmetry representatives; all disjoint "
            "exceptional-exceptional blocks unrestricted"
        ),
    }
    if write_dimacs:
        path = Path(f"scratch_e77_sat_exact_rep{branch_index}.cnf")
        with path.open("w", encoding="ascii", newline="\n") as handle:
            handle.write(f"p cnf {pool.top} {len(clauses)}\n")
            for clause in clauses:
                handle.write(" ".join(map(str, clause)) + " 0\n")
        meta["cnf_path"] = str(path)
        meta["cnf_sha256"] = hashlib.sha256(path.read_bytes()).hexdigest().upper()
    return clauses, edge_variables, edge, full_variables, meta


def solve_one(branch_index, out_queue):
    from pysat.solvers import Solver

    started = time.monotonic()
    clauses, _edge_variables, edge, full_variables, meta = build_cnf(branch_index)
    built = time.monotonic()
    with Solver(name="cadical195", bootstrap_with=clauses) as solver:
        answer = solver.solve()
        model = solver.get_model() if answer else None
        stats = solver.accum_stats()
    record = {
        "branch_index": branch_index,
        "status": "SAT" if answer else "UNSAT",
        "build_seconds": round(built - started, 3),
        "solve_seconds": round(time.monotonic() - built, 3),
        "meta": meta,
        "stats": stats,
        "formal_proof_certificate": None,
    }
    if model:
        positive = {literal for literal in model if literal > 0}
        selected = set()
        for pair, identifier in full_variables.items():
            value = edge(*pair)
            if value is True or (type(value) is int and value in positive):
                selected.add(identifier)
        checked = verify(selected)
        record["verification"] = {key: value for key, value in checked.items() if key != "edges"}
        record["positive_full_edge_variables"] = sorted(selected) if checked["ok"] else []
        if checked["ok"]:
            Path(f"scratch_e77_sat_exact_solution_rep{branch_index}.json").write_text(
                json.dumps(checked, indent=2) + "\n", encoding="utf-8"
            )
    out_queue.put(record)


def run_portfolio(seconds, max_parallel):
    context = mp.get_context("spawn")
    records = {}
    count = 3
    for offset in range(0, count, max_parallel):
        batch = list(range(offset, min(count, offset + max_parallel)))
        out_queue = context.Queue()
        processes = {}
        for branch_index in batch:
            process = context.Process(target=solve_one, args=(branch_index, out_queue))
            process.start()
            processes[branch_index] = process
        deadline = time.monotonic() + seconds
        while not all(index in records for index in batch):
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                break
            try:
                record = out_queue.get(timeout=min(1.0, remaining))
            except queue.Empty:
                continue
            records[record["branch_index"]] = record
        for branch_index, process in processes.items():
            if process.is_alive():
                process.terminate()
                process.join(10)
            else:
                process.join()
            records.setdefault(branch_index, {
                "branch_index": branch_index,
                "status": "UNKNOWN",
                "wall_limit_seconds": seconds,
                "exit_code_after_termination": process.exitcode,
                "formal_proof_certificate": None,
            })
    ordered = [records[index] for index in range(count)]
    result = {
        "model": "exact compact E0=77, three exhaustive local representatives",
        "solver": "CaDiCaL 1.9.5 via PySAT",
        "seconds_per_parallel_batch": seconds,
        "max_parallel": max_parallel,
        "coverage_source": str(REPS_PATH),
        "status": (
            "SAT" if any(row["status"] == "SAT" for row in ordered)
            else "UNSAT" if all(row["status"] == "UNSAT" for row in ordered)
            else "UNKNOWN"
        ),
        "proof_status": "no independently checked UNSAT certificate",
        "records": ordered,
    }
    RESULT_PATH.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--branch", type=int, choices=range(3))
    parser.add_argument("--build-only", action="store_true")
    parser.add_argument("--write-dimacs", action="store_true")
    parser.add_argument("--seconds", type=float, default=0)
    parser.add_argument("--max-parallel", type=int, default=3)
    args = parser.parse_args()
    if args.branch is not None:
        clauses, _variables, _edge, _full, meta = build_cnf(
            args.branch, write_dimacs=args.write_dimacs
        )
        meta["clauses_recount"] = len(clauses)
        BUILD_PATH.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(meta), flush=True)
        if not args.build_only:
            out_queue = mp.get_context("spawn").Queue()
            solve_one(args.branch, out_queue)
            print(json.dumps(out_queue.get()), flush=True)
    elif args.seconds > 0:
        result = run_portfolio(args.seconds, min(3, max(1, args.max_parallel)))
        print(json.dumps({
            "status": result["status"],
            "counts": {
                status: sum(row["status"] == status for row in result["records"])
                for status in ("SAT", "UNSAT", "UNKNOWN")
            },
        }), flush=True)
    else:
        parser.error("use --branch and/or --seconds")


if __name__ == "__main__":
    mp.freeze_support()
    main()
