"""Exact leverage tests for the rank-three E0=71 defect profiles.

For the 84-vertex outer graph, let U be the normalized coarse-fibre
incidence, Z the 21 by 21 Gram-circulation defect, and R=8W where
W=(I-UU^T)BU.  On the 70-dimensional cycle space the -4 and +3 spectral
projectors have, on the 14-dimensional coarse-cycle subspace, blocks

    E_-4: A=Z/28,       cross=-R/56,
    E_+3: A=I-Z/28,     cross= R/56.

The projector onto the range generated by the coarse block is dominated by
the full projector.  Since their coordinate diagonals are respectively
5/14 and 10/21, every scaled row r of R must satisfy

    (Z_G-r) Z^+ (Z_G-r)^T <= 40,
    (28K_G-Z_G+r) (28K-Z)^+ (28K_G-Z_G+r)^T <= 160/3,

where G is the fibre containing the coordinate and K is the orthogonal
projector onto the coarse cycle space.  Keeping the full row of E U is
essential here; a bound using only the bottom-left cross block is invalid.

This script evaluates those exact necessary inequalities on every integral
row pattern already frozen in the source-724/source-2601 rank-three probe.
It does not regenerate any order-eight class or run an E0=71 census.
"""

from __future__ import annotations

from fractions import Fraction
import hashlib
import itertools
import json
import os
from pathlib import Path


INPUT = Path("scratch_theory_e71_defect_rank_probe.json")
OUTPUT = Path("scratch_theory_e71_projector_leverage_probe.json")
SUPPORTS = tuple(itertools.combinations(range(7), 2))


def rref(matrix: list[list[Fraction]]):
    matrix = [row[:] for row in matrix]
    rows = len(matrix)
    columns = len(matrix[0]) if rows else 0
    pivot_columns: list[int] = []
    pivot_row = 0
    for column in range(columns):
        pivot = next(
            (row for row in range(pivot_row, rows) if matrix[row][column]),
            None,
        )
        if pivot is None:
            continue
        matrix[pivot_row], matrix[pivot] = matrix[pivot], matrix[pivot_row]
        scale = matrix[pivot_row][column]
        matrix[pivot_row] = [value / scale for value in matrix[pivot_row]]
        for row in range(rows):
            if row == pivot_row or not matrix[row][column]:
                continue
            scale = matrix[row][column]
            matrix[row] = [
                left - scale * right
                for left, right in zip(matrix[row], matrix[pivot_row])
            ]
        pivot_columns.append(column)
        pivot_row += 1
        if pivot_row == rows:
            break
    return matrix, pivot_columns


def solve_consistent(matrix: list[list[int]], target: list[int]):
    size = len(matrix)
    augmented = [
        [Fraction(value) for value in matrix[row]] + [Fraction(target[row])]
        for row in range(size)
    ]
    reduced, pivots = rref(augmented)
    assert size not in pivots
    solution = [Fraction(0) for _ in range(size)]
    for row, column in enumerate(pivots):
        if column < size:
            solution[column] = reduced[row][-1]
    assert all(
        sum(Fraction(matrix[i][j]) * solution[j] for j in range(size))
        == target[i]
        for i in range(size)
    )
    return solution


def dot(left, right):
    return sum(Fraction(a) * Fraction(b) for a, b in zip(left, right))


def encode(value: Fraction):
    return str(value.numerator) if value.denominator == 1 else str(value)


def atomic_json(path: Path, value) -> None:
    temporary = path.with_suffix(path.suffix + f".{os.getpid()}.tmp")
    temporary.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
    temporary.replace(path)


def main() -> None:
    raw = INPUT.read_bytes()
    source = json.loads(raw)
    rows_out = []
    overall_minus4 = Fraction(0)
    overall_plus3 = Fraction(0)
    total_patterns = 0
    for profile in source["rows"]:
        Z = [[int(value) for value in row] for row in profile["Z"]]
        size = len(Z)
        incidence = [
            [int(vertex in support) for support in SUPPORTS]
            for vertex in range(7)
        ]
        gram_inverse = [
            [Fraction(int(i == j), 5) - Fraction(1, 60) for j in range(7)]
            for i in range(7)
        ]
        coarse_cycle = [
            [
                Fraction(int(i == j))
                - sum(
                    Fraction(incidence[a][i])
                    * gram_inverse[a][b]
                    * Fraction(incidence[b][j])
                    for a in range(7)
                    for b in range(7)
                )
                for j in range(size)
            ]
            for i in range(size)
        ]
        plus3_denominator = [
            [28 * coarse_cycle[i][j] - Z[i][j] for j in range(size)]
            for i in range(size)
        ]
        exceptional = [tuple(item) for item in profile["exceptional_supports"]]
        pattern_rows = []
        max_minus4 = Fraction(0)
        max_plus3 = Fraction(0)
        violating_minus4 = 0
        violating_plus3 = 0
        for fibre in profile["rank_three_integer_row_patterns"]["by_source_fibre"]:
            source_support = tuple(fibre["source_support"])
            source_index = SUPPORTS.index(source_support)
            values = []
            for index, pattern in enumerate(fibre["patterns"]):
                residual_short = [
                    int(value) for value in pattern["scaled_W_row_on_exceptional"]
                ]
                residual = [0] * size
                for support, value in zip(exceptional, residual_short):
                    support_index = SUPPORTS.index(support)
                    residual[support_index] = value
                minus4_row = [
                    Z[source_index][column] - residual[column]
                    for column in range(size)
                ]
                plus3_row = [
                    28 * coarse_cycle[source_index][column]
                    - Z[source_index][column]
                    + residual[column]
                    for column in range(size)
                ]
                z_solution = solve_consistent(Z, minus4_row)
                plus3_solution = solve_consistent(
                    plus3_denominator, plus3_row
                )
                minus4 = dot(minus4_row, z_solution)
                plus3 = dot(plus3_row, plus3_solution)
                assert minus4 >= 0 and plus3 >= 0
                max_minus4 = max(max_minus4, minus4)
                max_plus3 = max(max_plus3, plus3)
                violating_minus4 += int(minus4 > 40)
                violating_plus3 += int(plus3 > Fraction(160, 3))
                values.append(
                    {
                        "pattern_index": index,
                        "minus4_leverage": encode(minus4),
                        "plus3_leverage": encode(plus3),
                    }
                )
                total_patterns += 1
            pattern_rows.append(
                {
                    "source_support": fibre["source_support"],
                    "patterns": values,
                }
            )
        overall_minus4 = max(overall_minus4, max_minus4)
        overall_plus3 = max(overall_plus3, max_plus3)
        rows_out.append(
            {
                "key": profile["key"],
                "Z_rank": profile["Z_rank"],
                "patterns_checked": sum(len(item["patterns"]) for item in pattern_rows),
                "maximum_minus4_leverage": encode(max_minus4),
                "minus4_cap": "40",
                "minus4_violations": violating_minus4,
                "maximum_plus3_leverage": encode(max_plus3),
                "plus3_cap": "160/3",
                "plus3_violations": violating_plus3,
                "by_source_fibre": pattern_rows,
            }
        )
    result = {
        "status": "EXACT_E71_PROJECTOR_LEVERAGE_PROBE_COMPLETE",
        "input": {str(INPUT): hashlib.sha256(raw).hexdigest().upper()},
        "derivation": {
            "minus4_compression": "A=Z/28",
            "minus4_cross": "C=-R/56",
            "minus4_coordinate_diagonal": "5/14",
            "minus4_inequality": "(Z_G-r) Z^+ (Z_G-r)^T <= 40",
            "plus3_compression_on_coarse_cycle_space": "A=K-Z/28",
            "plus3_cross": "C=R/56",
            "plus3_coordinate_diagonal": "10/21",
            "plus3_inequality": "(28K_G-Z_G+r) (28K-Z)^+ (28K_G-Z_G+r)^T <= 160/3",
        },
        "profiles_checked": len(rows_out),
        "patterns_checked": total_patterns,
        "overall_maximum_minus4_leverage": encode(overall_minus4),
        "overall_maximum_plus3_leverage": encode(overall_plus3),
        "rows": rows_out,
        "conclusion": (
            "These are exact pointwise spectral-projector leverage tests. "
            "A positive violation excludes its row pattern; zero violations "
            "would mark a scoped boundary rather than an E0 lower bound."
        ),
        "submission_txt_written": False,
    }
    atomic_json(OUTPUT, result)
    print(
        json.dumps(
            {
                "path": str(OUTPUT),
                "status": result["status"],
                "profiles_checked": result["profiles_checked"],
                "patterns_checked": total_patterns,
                "overall_maximum_minus4_leverage": encode(overall_minus4),
                "overall_maximum_plus3_leverage": encode(overall_plus3),
                "total_violations": sum(
                    row["minus4_violations"] + row["plus3_violations"]
                    for row in rows_out
                ),
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
