"""Verify affine-parity membership witness from raw neighborhoods, not elimination code."""
from datetime import datetime,timezone
from itertools import combinations
import json
import platform
import subprocess
import sys
import audit_20260917_partial_matching as h

ROOT=h.ROOT;D=ROOT/'acceleration/results/20260917_two_coordinate_binary_span';T=ROOT/'acceleration/results/20260917_partial_two_matchings'
def main():
    bindings={}
    def read(p):
        bindings[h.key(p)]=h.digest(p);d=json.loads(p.read_bytes())
        for f,v in d.get('inputs_sha256',{}).items():h.require(h.digest(ROOT/f)==v,'changed dependency');bindings[h.key(ROOT/f)]=v
        return d
    manifest=read(D/'manifest.json');summary=read(D/'summary.json');cert=read(D/'certificate.json')
    h.require(h.digest(D/'certificate.json')=='125beecb87fb5941c040790d54c5afb058c31acfd12458ac333317f406be8d0f','certificate pin')
    for name,pin in [('two_matchings/summary.json','f3d2ba90be5e8c27bc64c2e4941174d36fc3ddfcbc29ce25da872df652383acb'),('two_matching_moments.json','5af1f353a70a16fc5f915195b911d782e360ffc0690463936b7a9dea983197ed')]:
        p=ROOT/'acceleration/results/20260917_independent_review'/name;h.require(h.digest(p)==pin,'prior independent audit pin');read(p)
    primary=read(T/'manifest.json');tables=[[int(s,16)for s in read(T/f'domain_{u:02d}.json')['domain_masks_hex']]for u in range(84)];offsets=[0]
    for table in tables:offsets.append(offsets[-1]+len(table))
    h.require(offsets[-1]==89308,'population');labels=[(2*a+s,2*b+t)for a,b in combinations(range(7),2)for s in range(2)for t in range(2)]
    known=[set()for _ in range(84)]
    for a,b in primary['remaining_fixed_K_edges_outer']:known[a].add(b);known[b].add(a)
    unknown=list(map(tuple,primary['unknown_edges_outer']));eid={e:i for i,e in enumerate(unknown)};pairs=list(combinations(range(84),2));pid={e:i for i,e in enumerate(pairs)};hard=1884
    def feature(u,i):
        h.require(type(u)is int and type(i)is int and 0<=u<84 and 0<=i<len(tables[u]),'domain identity')
        selected=set(h.bits(tables[u][i]));neighbors=known[u]|selected;h.require(len(neighbors)==12,'full neighborhood');v=1<<u
        for w in selected:
            e=tuple(sorted((u,w)));v^=1<<(84+eid[e])
            if u<w:v^=1<<(hard+pid[e])
        for e in combinations(sorted(neighbors),2):v^=1<<(hard+pid[e])
        return v
    refs=[feature(u,0)for u in range(84)];h.require(cert['reference_global_columns']==offsets[:-1],'reference IDs')
    rhs=(1<<84)-1
    for a,b in pairs:
        r=2-len(set(labels[a])&set(labels[b]))-int(b in known[a])
        if r%2:rhs^=1<<(hard+pid[a,b])
    target=rhs
    for v in refs:target^=v
    h.require(target==int(cert['target_hex'],16),'raw affine target')
    selected=cert['selected_original_ids'];globals_=cert['selected_global_columns'];h.require(len(selected)==len(globals_)==1837 and len(set(globals_))==1837,'witness uniqueness')
    result=0;nonzero=None
    for e,g in zip(selected,globals_):
        u,i=e['center'],e['original_id'];v=feature(u,i)^refs[u];h.require(g==offsets[u]+i,'global ID mapping');result^=v
        if v:nonzero=v
    h.require(result==target,'affine span witness falsified')
    h.require(result!=(target^1)and nonzero is not None and (result^nonzero)!=target,'target/removal corruption controls')
    for bad in[(84,0),(0,len(tables[0])),(0,-1)]:
        try:feature(*bad)
        except ValueError:pass
        else:raise ValueError('corrupt ID accepted')
    for p in(__file__,h.__file__,ROOT/'uv.lock'):bindings[h.key(p)]=h.digest(p)
    h.require(all(h.digest(ROOT/f)==v for f,v in bindings.items()),'changed input')
    report=dict(status='INDEPENDENT_TWO_COORDINATE_BINARY_AFFINE_MEMBERSHIP_PASS',timestamp=datetime.now(timezone.utc).isoformat(),source_commit=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),command=[sys.executable,*sys.argv],cwd=str(ROOT),python=platform.python_version(),inputs_sha256=bindings,statement='The exact5370-row RHS lies in the affine F2 space generated by the complete original two-coordinate star columns, as witnessed by these1837 listed differences from84first-domain reference columns.',frozen_population=89308,witness_difference_columns_checked=1837,reference_columns_checked=84,witness_centers=len({e['center']for e in selected}),all_witness_entries_checked=True,full_population_reenumerated=False,full_rank_claimed=False,producer_imported=False,method='Rebuilt parity features by direct full outer-neighborhood pair counting, reciprocity incidence and simplex membership, without serialized matrix or producer elimination imports. Recomputed RHS and checked exact XOR witness plus all original/global IDs.',controls=dict(corrupted_target='REJECT',deleted_nonzero_difference='REJECT',out_of_range_or_negative_ID=3),shared_components=['Python standard library','prior independent raw-domain artifact helpers','pinned complete-domain and necessary-model reviews'],limitations=['Linear parity relaxation survives only; no one-star-per-center graph, integer solution or real LP feasibility follows.','Producer partial basis rank and processed-column count were not independently reproduced and are not approved by this report.','No contradiction with the independently positive real moment support bound; these are different relaxations.'])
    out=ROOT/'acceleration/results/20260917_independent_review/two_coordinate_binary_span.json'
    with out.open('x')as f:json.dump(report,f,indent=2)
    print(report['status'],h.digest(out))
if __name__=='__main__':main()
