"""Bind independently checked integer support evidence to an exact conditional claim."""
from datetime import datetime,timezone
from pathlib import Path
from fractions import Fraction
import json,subprocess,sys
import audit_20260917_partial_matching as h
ROOT=h.ROOT;OUT=ROOT/'acceleration/results/20260917_independent_review'
pins={'six_gpu_support.json':'0814b6d5e660b876247cf83dc4e37cfaa0e86ec1d1b05b59ab8b6fd63ebbcf80','six_matchings/summary.json':'051a57b2fc1b5353a6100b949f86674483cff686c4f797f4f1ad8b037d7f3768','six_coordinate_matching_filter/summary.json':'05d4284f04fb5c84491394695c6f56a3e5517302ae95c1885b27592cfed78a7f','six_filtered_moments.json':'f27467b03a34fe3ea3adec4e537585e71d5697f4e63562cdd43d7e6822c8f3e7'}
bindings={};reviews={}
for name,pin in pins.items():
    path=OUT/name;h.require(h.digest(path)==pin,'independent review pin');bindings[h.key(path)]=pin;reviews[name]=json.loads(path.read_bytes())
audit=reviews['six_gpu_support.json'];h.require(audit['status']=='INDEPENDENT_SIX_COORDINATE_GPU_EXACT_SUPPORT_ATTEMPTS_PASS'and audit['attempt_population']==6 and audit['positive_attempts']==4,'complete support review')
best=max(audit['attempts'],key=lambda r:Fraction(r['numerator'],r['denominator']));h.require(best['numerator']==906048 and best['denominator']==1048576 and best['strictly_positive'],'positive exact result')
manifest=ROOT/'acceleration/results/20260917_partial_six_matchings/manifest.json';scope=json.loads(manifest.read_bytes());h.require(len(scope['remaining_fixed_K_edges_outer'])==132 and len(scope['unknown_edges_outer'])==2040 and len(scope['freed_legal_matching_edges_outer'])==360,'scope counts')
h.require(reviews['six_matchings/summary.json']['domain_choices']==879449 and audit['independently_rejected_choices']==166728 and audit['retained_choices']==712721 and 166728+712721==879449,'coverage composition')
for path in(manifest,Path(__file__),Path(h.__file__),ROOT/best['certificate_path']):bindings[h.key(path)]=h.digest(path)
statement='For every symmetric binary zero-diagonal99-by99 matrix A retaining the fixed189-edge labeled root scaffold and132fixedK edges while respecting all prescribed absences in the pinned six-coordinate manifest, A^2=12I-A+2J fails. Only the360freed support-legal same-sign-coordinate edges at rootgroups0,1,2 and1680disjoint-support edges may vary.'
record=dict(status='INDEPENDENT_SIX_COORDINATE_EXCLUSION_CLAIM_BINDING_PASS',claim_id='C-PARTIAL-K-SIX-COORDINATE-EXCLUSION',claim_revision=1,recommendation='VERIFIED',statement=statement,timestamp=datetime.now(timezone.utc).isoformat(),source_commit=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),command=[sys.executable,*sys.argv],cwd=str(ROOT),inputs_sha256=bindings,exact_positive_bound={'numerator':906048,'denominator':1048576,'reduced':'14157/16384'},dependencies=[dict(id='C-PARTIAL-K-SIX-COORDINATE-DOMAINS',revision=1,relation='coverage'),dict(id='C-PARTIAL-K-SIX-COORDINATE-NEIGHBORHOOD-MATCHING-FILTER',revision=1,relation='uses_result'),dict(id='C-PARTIAL-K-SIX-COORDINATE-MATCHING-FILTERED-MOMENT-ENCODING',revision=1,relation='uses_result')],written_review='Independent complete enumeration covers every local star of every completion in this exact prescribed-zero family. The independently checked necessary neighborhood matching filter rejects166728stars and retains712721, with exact original-ID complements in each of84domains. A hypothetical completion yields a one-hot reciprocal point with zero full-neighborhood moment residual in the necessary filtered model. Arbitrary signed reciprocity weights and clipped moment weights yield the exact support lower bound. Separate raw-neighborhood Pythoninteger checking evaluated every retained star for allsix weight sets, reproduced all84maxima and verified four positive bounds. In particular residualL1>=14157/16384>0 contradicts the completion point. No solver convergence/validity, floating arithmetic certificate, numerical upper bound, or converse equivalence is used.',verification_kind='Independent derivation plus independent artifact checking; prior complete-domain/filter/encoding audits explicitly pinned.',reviewer='independent_verifier agent; distinct from structural_continuation producer',artifact_review_outcome='PASS',target_resolution='UNKNOWN',external_peer_review=False,limitations=['Conditional132fixedK/prescribed-zero family exclusion only; not unrestricted nonexistence.','No matching-configuration cardinality, target-wide coverage denominator, nontrivial automorphism, or universal labeling restriction is assumed.','The empirical GPU calibration is not a mathematical premise for validity of the independently checked arbitrary integer weights.'])
path=OUT/'six_exclusion_claim_binding.json'
with path.open('x')as f:json.dump(record,f,indent=2)
print(record['status'],h.digest(path))
