"""Bind the completed independent degree-bound review to two precise revisions."""
from datetime import datetime,timezone
from hashlib import sha256
from pathlib import Path
import json,platform,subprocess,sys

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'acceleration/results/20260930_independent_review/degree_block_gram'
def digest(p):return sha256(Path(p).read_bytes()).hexdigest()
def save(p,d):
    with p.open('x')as f:json.dump(d,f,indent=2)
def main():
    p=OUT/'summary.json';assert digest(p)=='8030415e025dd175aaba62879acf72dcffdf08076c435efe023a0e3935c9552d';audit=json.loads(p.read_bytes())
    assert audit['status']=='INDEPENDENT_DEGREE_BLOCK_GRAM_BOUND_AND_CUT_PASS'and audit['bound_evaluations']==31 and audit['edge_variables']==780 and audit['degree_equations']==160
    bindings={p.relative_to(ROOT).as_posix():digest(p)}
    for source in[Path(__file__).resolve(),ROOT/'acceleration/audit_20260930_degree_block_gram.md',ROOT/'acceleration/audit_20260930_degree_block_gram.py',ROOT/'uv.lock']:
        bindings[source.relative_to(ROOT).as_posix()]=digest(source)
    timestamp=datetime.now(timezone.utc).isoformat()
    common=dict(recommendation='VERIFIED',review_state='CLEAR',verifier='/root/state_literature_audit independent checking agent',timestamp=timestamp,source_commit=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),command=[sys.executable,*sys.argv],working_directory=str(ROOT),python=platform.python_version(),inputs_sha256=bindings,shared_components=audit['shared_components'],controls=audit['controls'],unrestricted_target_resolution=False,external_review=False)
    lemma=dict(**common,status='INDEPENDENT_DEGREE_BLOCK_UPPER_LEMMA_BINDING_PASS',claim_id='C-ROOK-DEGREE-BLOCK-GRAM-UPPER-BOUND',claim_revision=1,kind='mathematical result',basis=['DERIVED','COMPUTED'],statement='For every integer vector on the59vertices and every fixed-value pattern admitting a completion of the160degree equations in the pinned780edge model, the exact maximum of its quadratic for27I-9A+J over that degree-only relaxation equals its fixed affine constant plus the ten independent degree-block maxima. A certified strictly negative such upper bound forbids that pattern in every target extension of this fixed scaffold.',scope='The precise frozen central-factor scaffold, its780distinct Boolean edges and160degree equations. Four internal10vertex perfect-matching blocks, four10by10 perfect-matching blocks and two10by10 degree-two blocks. No claim of coverage of all rook embeddings or all targets.',assumptions=['The fixed pattern is degree-feasible; all31 reviewed patterns have separately checked attaining assignments.','Each certificate uses exact arithmetic and covers the entire relevant block, including forced values.'],dependencies=[dict(id='C-ROOK-FOUR-FACTOR-WINDOW-CNF-ENCODING',revision=1,relation='coverage'),dict(id='C-TARGET-GRAM-PSD-AND-SUPPORT-NOGOODS',revision=1,relation='uses_result')],verification_type='Independent written derivation plus exact finite block/degree coverage audit; independent DP and dual-certificate checking calibrate the implementation.',proof='acceleration/audit_20260930_degree_block_gram.md',checked_scope=dict(variables=780,degree_equations=160,block_partition=10,raw_vectors=9,internal_DP_certificates=124,bipartite_primal_dual_certificates=186),limitations=['The common-neighbor constraints are discarded; positive relaxed maxima are not feasible target graphs.','This theorem gives a sufficient rejection method, not a complete characterization of target extensions.','No independent external peer review or novelty claim.'])
    save(OUT/'lemma_claim_binding.json',lemma)
    clause=[7,45,82,-151,-158,-193,255,-272,-347,362,417,443];assert audit['final_clause']==clause and audit['exact_final_upper']==-176426969710399200
    cut=dict(**common,status='INDEPENDENT_DEGREE_BLOCK12_CUT_BINDING_PASS',claim_id='C-ROOK-DEGREE-BLOCK-GRAM-CUT-12',claim_revision=1,kind='exclusion',basis=['DERIVED','COMPUTED'],statement='Every Conway99target extension of the exact pinned780edge frozen-central-factor scaffold satisfies the clause[7,45,82,-151,-158,-193,255,-272,-347,362,417,443]. Its falsifying fixed-value pattern has exact maximum Gram quadratic -176426969710399200 over the larger degree-only relaxation, so no target extension realizes that pattern.',scope='One12literal conditional pattern in one fixed central-factor scaffold; all780free edge labels use model SHA25626908e992235e307cfc6145275deb3d2765a930c7c59a774c9a7bc42f2f0f95e. This does not exclude the whole scaffold or the unrestricted target.',assumptions=['Target adjacency satisfies the exact99vertex identity.','The target induces this particular fixed scaffold with the pinned variable labeling.'],dependencies=[dict(id='C-ROOK-DEGREE-BLOCK-GRAM-UPPER-BOUND',revision=1,relation='uses_result'),dict(id='C-ROOK-FOUR-FACTOR-WINDOW-CNF-ENCODING',revision=1,relation='encoding_equivalence')],verification_type='Independent exact raw-artifact checking and conditional exclusion derivation',exact_upper=audit['exact_final_upper'],nogood_clause=clause,encoding_model_sha256=audit['encoding_model_sha256'],base_cnf_sha256=audit['base_cnf_sha256'],certificate_path=audit['cut_package'],certificate_sha256=audit['cut_package_sha256'],block_certificate_path=audit['final_certificate'],block_certificate_sha256=audit['final_certificate_sha256'],clause_path=audit['clause_path'],clause_sha256=audit['clause_sha256'],counts=dict(unfixed_vectors_checked=9,unfixed_negative_bounds=0,bound_evaluations=31,initial_literals=21,deletion_attempts=21,accepted_deletions=9,final_literals=12,DP_values_checked=audit['DP_values_checked'],dual_inequalities_checked=audit['dual_inequalities_checked']),limitations=audit['limitations']+['The clause is shorter syntactically than its21literal ancestor; no separate increase in excluded degree-feasible assignments or solver performance is claimed.','No percentage of the unrestricted target search is defined.'])
    save(OUT/'cut_claim_binding.json',cut)
    print(json.dumps(dict(lemma_sha256=digest(OUT/'lemma_claim_binding.json'),cut_sha256=digest(OUT/'cut_claim_binding.json'))))
if __name__=='__main__':main()
