"""New wave27 catalog source; previous executed catalog is immutable."""
import ast,json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];A=ROOT/'acceleration';B='acceleration/results/20260930_';I=B+'independent_review/';inv=json.loads((ROOT/(B+'twentyseventh_candidate_inventory/inventory.json')).read_bytes());assert hashlib.sha256((ROOT/(B+'twentyseventh_candidate_inventory/inventory.json')).read_bytes()).hexdigest()=='381d1130d419894a9cfd916a5c41faee637d97bf850bb046e472f5d26f7cd4ba'
dirs=inv['explicit_directories']+[B+'twentyseventh_candidate_inventory',B+'twentyseventh_raw_recovery',B+'twentyseventh_recovery_controls']
files=inv['explicit_files']+['acceleration/'+x for x in['complete_20260930_exact_eight_campaign_native_v2.py','revise_20260930_exact_eight_population_inventory.py','prepare_20260930_twentyseventh_inventory_source.py','prepare_20260930_twentyseventh_catalog_source.py','prepare_20260930_twentyseventh_recovery_helpers.py','package_20260930_twentyseventh_catalog.py','package_20260930_twentyseventh_catalog_spec.md','package_20260930_twentyseventh_recovery.py','package_20260930_twentyseventh_recovery_spec.md','recover_20260930_twentyseventh_raw_artifacts.py','check_20260930_twentyseventh_recovery_controls.py']]
values=dict(REGISTRATIONS=[r['directory']for r in inv['registration_chain']],DIRECTORIES=dirs,FILES=sorted(set(files)),FORBIDDEN_DIRECTORIES=[B+'exact_eight_next32',I+'exact_eight_next32',I+'exact_eight_first12_union',I+'exact_eight_first12_union_v2',B+'exact_eight_explicit_batch_preparation_v2'],FORBIDDEN_TOKENS=['next32','NEXT32','first12_union','FIRST12_UNION','explicit_batch_v2','explicit_batch_preparation_v2'],PRIOR_CATALOG=B+'twentysixth_artifact_packaging/catalog.json',PRIOR_CATALOG_SHA='d27a41ee61c1ed7453682ae69dd5a041e94e47e91d2aacaaf9b9c429619e27fb',ALLOWED_OUTPUTS={B+'twentyseventh_preparation',B+'twentyseventh_artifact_packaging'})
old=A/'package_20260930_twentysixth_catalog.py';t=old.read_text(encoding='utf8').replace('package_20260930_twentysixth_recovery','package_20260930_twentyseventh_recovery');tree=ast.parse(t);lines=t.splitlines(keepends=True)
for n in reversed(tree.body):
    if isinstance(n,ast.Assign)and len(n.targets)==1 and isinstance(n.targets[0],ast.Name)and n.targets[0].id in values:lines[n.lineno-1:n.end_lineno]=[n.targets[0].id+'='+repr(values[n.targets[0].id])+'\n']
t=''.join(lines).replace('wave26','wave27').replace('WAVE26','WAVE27').replace('TWENTYSIXTH','TWENTYSEVENTH').replace('twentysixth_raw_recovery','twentyseventh_raw_recovery')
t=t.replace('8bcdad8f4b2e871b6c0bdf6ef72736033a8d84624af029e1b01c2951bc4b8146','5ea04f21e5964b6f987d00a600a69d4472bfebdd0fea7f564e4dfec1af5cb237').replace('==278','==286').replace("('VERIFIED','CLEAR'):273","('VERIFIED','CLEAR'):281").replace("ids.extend(receipt['new_claim_ids'])","ids.extend(receipt.get('new_claim_ids',[]))").replace('==11','==8').replace("('VERIFIED','CLEAR'):11","('VERIFIED','CLEAR'):8").replace('exact ordered eight-registration chain','exact ordered six-registration chain')
t=t.replace('7f8f2c99a0ddd50fdb4fce9eaf4100240ecb19c4c6dbc6946b7e27cec29d6cd6','d6d5e3933cd8294b4f4119c6ba495780a77cf19833ecb056598a863bbef11958').replace("{'outputs_sha256','input_sha256'}","{'outputs_sha256','input_sha256','checked_artifact_hashes'}")
t=t.replace('claim_population=278,new_claims=11,verified_clear=273','claim_population=286,new_claims=8,verified_clear=281')
t=t.replace("excluded_cohorts=['Wave27 next literal lift/source/native and PSD-kernel option scout.','Historical unregistered leftovers and protected user files.']","excluded_cohorts=['Wave28 next32 cohorts, explicit-builderv2, and first12 union.','Historical unregistered leftovers and protected user files.']")
t=t.replace("preserved_failures=['Census/algebra registrar initial failed attempt and corrected registrar.','Original wave26 report and separate scope clarification; no prior file changed.']","preserved_failures=['Original source-only native control failure and Windows text-codec setup failure, with fresh v2 source.','Original inventory catalogue-predicate failure and corrected full local-Gram reconstruction.','Original coverage audit failure and separate corrected report.','PSD intermediate CANDIDATE revision1 and promotion to VERIFIED revision2.']")
t=t.replace("preserved_failures=['Census/algebra registrar initial failed attempt and corrected registrar.','Original wave27 report and separate scope clarification; no prior file changed.']","preserved_failures=['Native preparation/source failures, inventory v1 and coverage v1 preserved unchanged.','PSD intermediate candidate revision1 and verified revision2 retained in registration chain.']")
t=t.replace('unexecuted_preparations=[]','unexecuted_preparations=[\'Source-only explicit build-batch interface v1; no additional build was executed by that preparation.\']')
t=t.replace("    claims=[c for c in ledger['claims']if c['id']in ids]","    promotion=json.loads((ROOT/(B+'twentyseventh_psd_promotion/summary.json')).read_bytes())\n    assert promotion['promoted_claim_ids']==['C-FIXED-HADAMARD-EXACT-EIGHT-SURVIVOR-PSD-SCREEN']and promotion['from_revision']==1 and promotion['to_revision']==2\n    claims=[c for c in ledger['claims']if c['id']in ids]")
needle="        if p not in cache:\n            path=ROOT/p;"
t=t.replace(needle,"        if p not in cache:\n            assert not any(token in p for token in FORBIDDEN_TOKENS)and p not in FORBIDDEN_FILES and not p.startswith('tools/'),('protected/future reference before read',p)\n            path=ROOT/p;")
new=A/'package_20260930_twentyseventh_catalog.py';ast.parse(t)
with new.open('x',encoding='utf8',newline='\n')as f:f.write(t)
print(json.dumps(dict(source_sha256=hashlib.sha256(new.read_bytes()).hexdigest(),directories=len(dirs),files=len(set(files)))))
