"""Freeze independently approved encoding/witness statements; no registry edits."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,platform,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];B='acceleration/results/20260930_independent_review/'
G=B+'count_interval_cnf/summary.json';O=B+'count_interval_constructed_object/summary.json';C=B+'count_interval_object_calibration/summary.json'
PINS={G:'03bc6b052a831eb0e5d3dacce7647ec88a81410e5f63ec81c88246575cd6baa6',O:'7deae0325b9acb8f97c3941503bc49dec9a2b0eb94c5f805411085ceb5e6e27a',C:'4573c816420efecf4c3542b30389214d3f10426005da1dc5e2ed720a0b1ebd56'}
def sha(p):
    with (ROOT/p).open('rb')as f:return hashlib.file_digest(f,'sha256').hexdigest()
def save(p,v):
    with p.open('x',encoding='utf-8',newline='\n')as f:json.dump(v,f,indent=2);f.write('\n')
def main():
    for p,h in PINS.items():assert sha(p)==h
    gates={p:json.loads((ROOT/p).read_bytes())for p in PINS};now=datetime.now(timezone.utc).isoformat();records=[]
    for kind,id_,statement,scope,report,dependencies in [
      ('encoding','C-FIXED-HADAMARD-COUNT-INTERVAL-ENCODING','For the exact pinned literal support and count domains, the 185963-variable7659287-clause CNF is satisfiable exactly for count tables satisfying the authenticated at-least-seven count CSP and all540 exact local-count-signature scalar Gram interval inequalities. Every full factor on that support with the prescribed Gram and all outside-column overlaps at most2 yields such a count table.','Exact necessary count-and-scalar-interval relaxation, not full-factor equivalence.',G,[('C-FIXED-HADAMARD-ARBITRARY-EXCEPTION-COUNT-MASTER-ENCODING','encoding_equivalence'),('C-FIXED-HADAMARD-COUNT-SIGNATURE-GRAM-INTERVALS','premise')]),
      ('construction','C-FIXED-HADAMARD-EIGHT-EXCEPTION-COUNT-INTERVAL-WITNESS','The pinned 185963-variable7659287-clause interval count formula has the complete saved constructed satisfying assignment242c6349604955f45fb103dc2221e62d70d3ccb417d8a31a8bc6e9e19724d0cc, which retains the authenticated155939 base variable values and independently decodes to count-profile d2b0c89bb1d8f0d75b47f541603e952618cebe9b7ecccd8e1b2c23a279ac8dd9 with eight exceptional groups.','One exact constructed count-relaxation witness; no native interval solver result and no factor.',O,[('C-FIXED-HADAMARD-COUNT-INTERVAL-ENCODING','encoding_equivalence'),('C-FIXED-HADAMARD-AT-LEAST-SEVEN-COUNT-CSP-WITNESS','derived_from')])]:
        g=gates[report];record=dict(id=id_,revision=1,statement=statement,kind=kind,basis=['DERIVED','COMPUTED']if kind=='encoding'else['COMPUTED'],status='VERIFIED',review_state='CLEAR',scope=scope,assumptions=['The exact immutable raw support, complete local catalogue, complete marginal domains and interval extrema bound by the separate independent premise gates.'],dependencies=[dict(id=i,revision=1,relation=r)for i,r in dependencies],verifier='/root/eight_domain_audit',recommendation='VERIFIED/CLEAR only within the declared relaxation scope.',evidence=[dict(path=report,sha256=PINS[report]),dict(path=C,sha256=PINS[C])],verification_records=[dict(claim_id=id_,claim_revision=1,verifier='/root/eight_domain_audit',kind='independent_artifact_checking_and_derivation'if kind=='encoding'else'independent_artifact_checking',timestamp=g['timestamp'],outcome='PASS',report_path=report,report_sha256=PINS[report],command=g['command'],cwd=g['cwd'],source_commit=g['source_commit'],artifact_hashes=g['inputs_sha256'],method='Own complete subset/channel/counter/clause reconstruction and exact preserved-body/gzip transport checks.'if kind=='encoding'else'All185963 variable IDs and7659287 actual clauses; literal count decoding, every direct-prefix auxiliary and all540 exact raw-core-derived interval bounds. Complete authentic base prefix preserved; no solver call.')],trusted_components=['Independently authenticated base encoding and root-reviewed complete interval extrema are explicit premises.','Shared frozen independently authored base Boolean/count/native-codec helpers; no producer imports.','Standard-library exact integer arithmetic and SHA256.'],limitations=['Unsummed full Gram, cross-group outside-column caps and residual D are absent.','Eight exceptional groups here do not imply any full-factor lift exists.','No target automorphism or unrestricted-target coverage is claimed.','Constructed witness mode requires no fabricated native output; the prepared native interval wrapper remained unused.'],artifact_availability='LOCAL_ONLY',availability_reason='Awaiting parent publication.',external_review=None,external_review_null_reason='Internal independent review only.',created_at=now,updated_at=now)
        records.append(record)
    out=ROOT/(B+'count_interval_claim_bindings');out.mkdir(exist_ok=False);source=Path(__file__).relative_to(ROOT).as_posix();inputs={**PINS,source:sha(source)}
    save(out/'manifest.json',dict(timestamp=now,source_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),command=[sys.executable,*sys.argv],cwd=str(ROOT),python=platform.python_version(),inputs_sha256=inputs,registry_changed=False))
    save(out/'claim_bindings.json',records);outputs={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT).as_posix())for p in out.iterdir()}
    save(out/'summary.json',dict(status='INDEPENDENT_COUNT_INTERVAL_CLAIM_BINDINGS_COMPLETE',inputs_sha256=inputs,outputs_sha256=outputs,claims=[dict(id=r['id'],revision=1,status='VERIFIED',review_state='CLEAR')for r in records],new_mathematical_check=False,registry_changed=False))
    print(json.dumps(dict(summary_sha256=sha((out/'summary.json').relative_to(ROOT).as_posix()),bindings_sha256=sha((out/'claim_bindings.json').relative_to(ROOT).as_posix()))))
if __name__=='__main__':main()
